### ISSUE TITLE
Cambiare "Trentino alto adige"

### ISSUE THREAD

**Issue by DaveParm** [nicolezatta/COVID19-Italy-phase2-enriched-dataset#45]
In regions_population.csv viene indicata la popolazione del "Trentino Alto Adige", tuttavia in tutto il resto della directory si fa (correttamente) riferimento alle due province autonome di Bolzano e Trento invece.

**Comment by nicolezatta** [comment]
Please write in English, in order to make it possible for everyone to understand. Anyway, I specified in README that Trentino stands for both PA Bolzano and PA Trento
